In [ ]:
Rmax=0.6
Residence_time = 20
N_cells = 2
Recovery = Rmax*(1-(1/(1+0.3*((Residence_time)**(N_cells)))))
Recovery

0.5950413223140496

In [ ]:
import scipy.optimize as optimize
from scipy.optimize import Bounds
from scipy.optimize import LinearConstraint
from scipy.optimize import NonlinearConstraint
import autograd.numpy as numpy
from autograd import grad, jacobian
from scipy.optimize import BFGS
from scipy.optimize import minimize
import numpy as np
volume = 0
N_splits = 0
N_cells = 0
Rmax = 0.6
param = [volume, N_splits, N_cells]
def cost_CP(param):
   return 711.8841*param[0]*param[1]*param[2] + 4179.24965*param[0]*param[1]*param[2]   #-> make volume, split and cells into 1 vector and use x[0] to refer to volume, x[1] to refer to N_splits and x[2] to refer to N_cells
                                                                                    #gradient_cost = grad(cost_CP)
                                                                                    #jacobian_cost = jacobian(cost_CP)
                                                                                    #print(jacobian_cost)
def recovery(param):
  return Rmax*(1-(1/(1+0.3*((param[0]/2)**(N_cells)))))
def jacobian_matrix(param):
  return [711.8841*param[1]*param[2] + 4179.24965*param[1]*param[2], 711.8841*param[0]*param[2] + 4179.24965*param[0]*param[2], 711.8841*param[0]*param[1] 
           + 4179.24965*param[0]*param[1]]

non_linear_constraint = NonlinearConstraint(cost_CP, 0,500000, jac = jacobian_matrix, hess=BFGS())

bounds = Bounds([9,2,1], [100,5,10])

#optimize starts here

initial_guess = np.array([9,2,5])
result = minimize(cost_CP, initial_guess,method='trust-constr', jac=jacobian_matrix, hess = BFGS(), constraints=non_linear_constraint
                  , options={'verbose':1}, bounds=bounds)
print(result.fun)
print(result.x)


`gtol` termination condition is satisfied.
Number of iterations: 19, function evaluations: 18, CG iterations: 28, optimality: 1.46e-11, constraint violation: 0.00e+00, execution time: 0.064 s.
88040.4675005202
[9.00000204 2.00000045 1.00000023]


In [ ]:
#assumptions: 
#same amount (5wt.% of solids is exiting every tank)   -> need to take into consideration -> need function of solid% removal at outlet tank.
#bubble size distribution is the same, bitumen attaches uniformly throughout the tank, does not affect solid removal
#all tanks have same volume

import scipy.optimize as optimize
from scipy.optimize import Bounds
from scipy.optimize import LinearConstraint
from scipy.optimize import NonlinearConstraint
import autograd.numpy as numpy
from autograd import grad, jacobian
from scipy.optimize import BFGS
from scipy.optimize import minimize
import numpy as np
Rmax = 0.6
#param = [volume, N_splits, N_cells]
param = np.array([10,0,0])
def cost_CP(param):
   return 711.8841*param[0]*param[1]*param[2] + 4179.24965*param[0]*param[1]*param[2]   #-> make volume, split and cells into 1 vector and use x[0] to refer to volume, x[1] to refer to N_splits and x[2] to refer to N_cells
                                                                                    #gradient_cost = grad(cost_CP)
                                                                                    #jacobian_cost = jacobian(cost_CP)
                                                                                    #print(jacobian_cost)
def recovery(param):
  return (Rmax*(1-(1/(1+0.3*((param[0]/2)**(param[2]))))))
def jacobian_matrix(param):
  return [711.8841*param[1]*param[2] + 4179.24965*param[1]*param[2], 711.8841*param[0]*param[2] + 4179.24965*param[0]*param[2], 711.8841*param[0]*param[1] 
           + 4179.24965*param[0]*param[1]]

non_linear_constraint1 = NonlinearConstraint(recovery,0.59,0.6, jac = '2-point', hess=BFGS())     #forcing recovery% to stay in between 0.59-0.5999 -> all values change by a large margin when narrowing down recovery% bounds

#non_linear_constraint2 = NonlinearConstraint(cost_CP,0,500000, jac = jacobian_matrix, hess=BFGS())
#new_recovery = -1*recovery(param)

bounds = Bounds([3,2,2], [100,20,20])  #->if N_splits=0 then all values including cost converge to 0

#optimize starts here

initial_guess = np.array([1,1,1])
result = minimize(cost_CP,initial_guess ,method='trust-constr', jac='2-point', hess = BFGS(), constraints=non_linear_constraint1
                  , options={'verbose':1}, bounds=bounds)
#result = minimize(cost_CP,initial_guess ,method='trust-constr', jac=jacobian_matrix, hess = BFGS(), constraints=[non_linear_constraint1, non_linear_constraint2]
#                  , options={'verbose':1}, bounds=bounds)
residence_time = (int(result.x[0]))/(2/int(result.x[1]))
print(result.fun)
print(result.x)
print(result)
print(residence_time)

`gtol` termination condition is satisfied.
Number of iterations: 137, function evaluations: 528, CG iterations: 149, optimality: 3.95e-09, constraint violation: 0.00e+00, execution time: 0.33 s.
280880.8553573119
[5.43656385 2.         5.28151006]
 barrier_parameter: 5.120000000000003e-08
 barrier_tolerance: 5.120000000000003e-08
          cg_niter: 149
      cg_stop_cond: 4
            constr: [array([0.59]), array([5.43656385, 2.        , 5.28151006])]
       constr_nfev: [528, 0]
       constr_nhev: [0, 0]
       constr_njev: [0, 0]
    constr_penalty: 148502.25853490972
  constr_violation: 0.0
    execution_time: 0.3304312229156494
               fun: 280880.8553573119
              grad: array([ 51665.14424313, 140440.42773438,  53181.92193904])
               jac: [array([[0.00955288, 0.        , 0.00983333]]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])]
   lagrangian_grad: array([-3.95287069e-09,  0.00000000e+00,  3.82269491e-09])
           message: '`gtol`

In [ ]:
#assumptions: 
#same amount (5wt.% of solids is exiting every tank)   -> need to take into consideration -> need function of solid% removal at outlet tank.
#bubble size distribution is the same, bitumen attaches uniformly throughout the tank, does not affect solid removal
#all tanks have same volume

import scipy.optimize as optimize
from scipy.optimize import Bounds
from scipy.optimize import LinearConstraint
from scipy.optimize import NonlinearConstraint
import autograd.numpy as numpy
from autograd import grad, jacobian
from scipy.optimize import BFGS
from scipy.optimize import minimize
import numpy as np
Rmax = 0.6
#param = [volume, N_splits, N_cells]
param = np.array([10000,0,0])
def cost_CP(param):
   return 711.8841*param[0]*param[1]*param[2] + 4179.24965*param[0]*param[1]*param[2]   #-> make volume, split and cells into 1 vector and use x[0] to refer to volume, x[1] to refer to N_splits and x[2] to refer to N_cells
                                                                                    #gradient_cost = grad(cost_CP)
                                                                                    #jacobian_cost = jacobian(cost_CP)
                                                                                    #print(jacobian_cost)
def recovery(param):
  return (Rmax*(1-(1/(1+0.3*((param[0]/(2/param[1]))**(param[2]))))))
def jacobian_matrix(param):
  return [711.8841*param[1]*param[2] + 4179.24965*param[1]*param[2], 711.8841*param[0]*param[2] + 4179.24965*param[0]*param[2], 711.8841*param[0]*param[1] 
           + 4179.24965*param[0]*param[1]]
def residence_time(param):
  return param[0]/(2*param[1])
def nonlinearconstraint(param):
  return [711.8841*param[0]*param[1]*param[2] + 4179.24965*param[0]*param[1]*param[2], Rmax*(1-(1/(1+0.3*((param[0]/(2/param[1]))**(param[2])))))]
def linearconstraint(param):
  return param[0]-1442*param[1]
non_linear_constraint1 = NonlinearConstraint(recovery,0.59,0.6, jac = '2-point', hess=BFGS())     #forcing recovery% to stay in between 0.59-0.5999 -> all values change by a large margin when narrowing down recovery% bounds
non_linear_constraint3 = NonlinearConstraint(residence_time, 50,600, jac = '2-point', hess=BFGS())
non_linear_constraint2 = NonlinearConstraint(cost_CP,0,500000, jac = jacobian_matrix, hess=BFGS())
#new_recovery = -1*recovery(param)
non_linear_constraint_true = NonlinearConstraint(nonlinearconstraint, [0,0.59],[50000,0.6], jac = '2-point', hess=BFGS())
linear_constraint = LinearConstraint([[1,-1442,0]], 0, 4000)
bounds = Bounds([3,1,1], [400,10,10])  #->if N_splits=0 then all values including cost converge to 0

#optimize starts here

initial_guess = np.array([1,1,1])
#result = minimize(cost_CP,initial_guess ,method='trust-constr', jac='2-point', hess = BFGS(), constraints=[non_linear_constraint_true, linear_constraint]
#                  , options={'verbose':1}, bounds=bounds)
result = minimize(cost_CP,initial_guess ,method='trust-constr', jac=jacobian_matrix, hess = BFGS(), constraints=[non_linear_constraint1]
                  , options={'verbose':1}, bounds=bounds)
#if result.x[1]<=1:
 # result.x[1]=1
#elif result.x[1]>=1.5 & result.x[1]<=2.5:
 # result.x[1]=2
#elif result.x[1]>2.5 & result.x[1]<=3.5:
 # result.x[1]=3
residence_time = result.x[0].astype(int)/((2/result.x[1].astype(int)))
print(result.fun)
print(result.x.astype(int))
print(result)
print(residence_time)

`xtol` termination condition is satisfied.
Number of iterations: 245, function evaluations: 259, CG iterations: 333, optimality: 1.60e-03, constraint violation: 0.00e+00, execution time: 0.52 s.
140440.42847836093
[5 1 5]
 barrier_parameter: 2.048000000000001e-09
 barrier_tolerance: 2.048000000000001e-09
          cg_niter: 333
      cg_stop_cond: 4
            constr: [array([0.59]), array([5.40469544, 1.00589626, 5.28151097])]
       constr_nfev: [1036, 0]
       constr_nhev: [0, 0]
       constr_njev: [0, 0]
    constr_penalty: 1.0
  constr_violation: 0.0
    execution_time: 0.5236139297485352
               fun: 140440.42847836093
              grad: array([ 25984.89223031, 139617.20865665,  26590.95650273])
               jac: [array([[0.00960921, 0.05163043, 0.00983333]]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])]
   lagrangian_grad: array([-1.59949015e-03, -3.29202548e-07,  1.56476302e-03])
           message: '`xtol` termination condition is satisfied.'
 

In [ ]:
param[0]

10

In [ ]:
import numpy as np
m=4472.9/(2*(np.pi))
m
n=26259/(2*np.pi)
n

4179.24965065008

In [ ]:
def f(params):
  #print(params)  <-- you'll see that the params is a numpy array
  height ,N_splits, N_cells = params
  return (34.851*(height)**2 +1992.5*height+12533)*(N_splits)*(N_cells/2)
initial_guess = [0,0,0]
result = optimize.minimize(f, initial_guess)
if result.success:
  fitted_params = result.x
  print(fitted_params)
else:
  raise ValueError(result.message)

[0. 0. 0.]


In [ ]:
from scipy.optimize import minimize
import numpy as np
f = lambda x: np.sin(x)  # function to be MAXIMIZED
res = minimize(lambda x: -f(x), 0)
print('Maximum {} attained at {}'.format(-res.fun, res.x))


Maximum 1.0 attained at [1.57079632]


In [ ]:
help ()


Welcome to Python 3.8's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.8/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".


You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.
